// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokeTradeCenter.Models;

namespace PokeTradeCenter.Migrations
{
    [DbContext(typeof(PokeTradeCenterContext))]
    [Migration("20181120083841_Add-Moves-Table")]
    partial class AddMovesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PokeTradeCenter.Models.Ad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Atk");

                    b.Property<int>("Def");

                    b.Property<int>("Hp");

                    b.Property<int>("Level");

                    b.Property<int?>("Move1ID");

                    b.Property<int?>("Move2ID");

                    b.Property<int?>("Move3ID");

                    b.Property<int?>("Move4ID");

                    b.Property<int?>("NatureID");

                    b.Property<int?>("PokemonID");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<bool>("Shiny");

                    b.Property<int>("SpeAtk");

                    b.Property<int>("SpeDef");

                    b.Property<int>("Speed");

                    b.HasKey("ID");

                    b.HasIndex("Move1ID");

                    b.HasIndex("Move2ID");

                    b.HasIndex("Move3ID");

                    b.HasIndex("Move4ID");

                    b.HasIndex("NatureID");

                    b.HasIndex("PokemonID");

                    b.ToTable("Ad");
                });

            modelBuilder.Entity("PokeTradeCenter.Models.MoveType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("MoveType");
                });

            modelBuilder.Entity("PokeTradeCenter.Models.Pokemon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Generation");

                    b.Property<string>("Name");

                    b.Property<int>("OrderNumber");

                    b.HasKey("ID");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("PokeTradeCenter.Models.PokemonMove", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("TypeID");

                    b.HasKey("ID");

                    b.HasIndex("TypeID");

                    b.ToTable("PokemonMove");
                });

            modelBuilder.Entity("PokeTradeCenter.Models.PokemonNature", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("PokemonNature");
                });

            modelBuilder.Entity("PokeTradeCenter.Models.Ad", b =>
                {
                    b.HasOne("PokeTradeCenter.Models.PokemonMove", "Move1")
                        .WithMany()
                        .HasForeignKey("Move1ID");

                    b.HasOne("PokeTradeCenter.Models.PokemonMove", "Move2")
                        .WithMany()
                        .HasForeignKey("Move2ID");

                    b.HasOne("PokeTradeCenter.Models.PokemonMove", "Move3")
                        .WithMany()
                        .HasForeignKey("Move3ID");

                    b.HasOne("PokeTradeCenter.Models.PokemonMove", "Move4")
                        .WithMany()
                        .HasForeignKey("Move4ID");

                    b.HasOne("PokeTradeCenter.Models.PokemonNature", "Nature")
                        .WithMany()
                        .HasForeignKey("NatureID");

                    b.HasOne("PokeTradeCenter.Models.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonID");
                });

            modelBuilder.Entity("PokeTradeCenter.Models.PokemonMove", b =>
                {
                    b.HasOne("PokeTradeCenter.Models.MoveType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID");
                });
#pragma warning restore 612, 618
        }
    }
}
